### ISSUE TITLE
Reseach Screen goes blank

### ISSUE THREAD

**Issue by TLHeart** [simon-82/ModVarietyPack#103] opened 2016-01-08 21:29 UTC
Open research screen, and it is blank... get this error in the log repeating forever.

Exception filling window for CommunityCoreLibrary.MainTabWindow_Research: System.NullReferenceException: Object reference not set to an instance of an object

  at CommunityCoreLibrary.MainTabWindow_Research+<>c.<RefreshSource>b__29_10 (CommunityCoreLibrary.HelpDef rpd) [0x00000] in <filename unknown>:0 

  at System.Linq.SortSequenceContext`2[CommunityCoreLibrary.HelpDef,System.String].Initialize (CommunityCoreLibrary.HelpDef[] elements) [0x00000] in <filename unknown>:0 

  at System.Linq.QuickSort`1[CommunityCoreLibrary.HelpDef].PerformSort () [0x00000] in <filename unknown>:0 

  at System.Linq.QuickSort`1+<Sort>c__Iterator21[CommunityCoreLibrary.HelpDef].MoveNext () [0x00000] in <filename unknown>:0 

  at System.Collections.Generic.List`1[CommunityCoreLibrary.HelpDef].AddEnumerable (IEnumerable`1 enumerable) [0x00000] in <filename unknown>:0 

  at System.Collections.Generic.List`1[CommunityCoreLibrary.HelpDef]..ctor (IEnumerable`1 collection) [0x00000] in <filename unknown>:0 

  at System.Linq.Enumerable+<CreateReverseIterator>c__IteratorF`1[CommunityCoreLibrary.HelpDef].MoveNext () [0x00000] in <filename unknown>:0 

  at System.Linq.Enumerable.Count[HelpDef](IEnumerable`1 source) [0x00000] in <filename unknown>:0 

  at CommunityCoreLibrary.MainTabWindow_Research.DoWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 

  at Verse.Window+<WindowOnGUI>c__AnonStorey1C3.<>m__EE (Int32 x) [0x00000] in <filename unknown>:0

**Comment by Karel-Kroeze** [comment] 2016-01-11 13:08
any idea when/how this happened exactly? It's a piece of CCL I'm responsible for...

**Comment by TLHeart** [comment] 2016-01-11 21:49
Sorry no idea what is causing this to happen... it is random at the moment. I can't even reproduce it from the same save file. 

But It does happen everytime I load the save file from planeton.rws located here:
https://www.dropbox.com/s/i41upyt4o2q0k01/Planeton.rws?dl=0

load the game click on the research tab, and click on any part of the research.

**Comment by Flow86** [comment] 2016-01-16 14:03
hi, i get the same thing, research tab completly blank here

**Comment by simon-82** [comment] 2016-01-24 11:56
I can't reproduce that error. And I never saw it happen randomly in any of my games. 
Maybe this is related to your other errors in issue #106? Mods not loading correctly?

**Comment by Flow86** [comment] 2016-01-25 06:40
ah I think I found what caused the problem: I had to deactivate and reactivate a random mod and then create a new plane: research tree is okay after that. perhaps some mod loading issue?

**Comment by Karel-Kroeze** [comment] 2016-01-25 08:33
Yeah, changing mods without reloading the game will lead to all kinds of
weirdness.

**Comment by simon-82** [comment] 2016-01-27 22:45
So the bug is just that? "Weirdness" from mods not loading correctly? Or did you find anything related to the log errors that are posted in the OP here @Karel-Kroeze? 
Can I close this then?

**Closed as completed** 2016-02-04 16:01 UTC
