### ISSUE TITLE
Colonist throwing job tick exceptions and ends up standing around doing nothing

### ISSUE THREAD

**Issue by Fredfirebat** [simon-82/ModVarietyPack#102] opened 2016-01-06 19:08 UTC
I'll post what my debug window says when I get a moment.
Any so I'm playing my second colony with the modpack and this happened to me in both. In the first it was my hunter who would throw the job tick thing I figured it was just because like an animal walked off map while he was trying to shoot it (sometimes from across the map as a side note some of the weapons don't show a range and people end up shooting from way too far away) but he would keep doing his job eventually. With this new group my colonist just started standing around outside my kitchen/cooler area. (Last side note cowboy hats and tuques don't show up in stockpiles but sometimes are wore in by raiders and at least the cowboy hat can be made at the hatters table, nothing like a pile of cowboy hats on the floor)
And I'll get the debug up as soon as I can

Regards, 
Fredfirebat

**Comment by simon-82** [comment] 2016-01-06 20:37
> hunter who would throw the job tick thing I figured it was just because like an animal walked off map while he was trying to shoot it (sometimes from across the map as a side note some of the weapons don't show a range and people end up shooting from way too far away)

Hunting from far away is an issue with the CombatRealisn mod. The weapons have reduced accuracy and bullets will hit trees/chunks/bushes. That's why hunting is better done with short range weapons. Weapons with very long range can't show the range-circle. It's a game limitation. You can see that when you change the range of a recipe on a table. When it gets over ~60 the circle dissapears.

> (Last side note cowboy hats and tuques don't show up in stockpiles but sometimes are wore in by raiders and at least the cowboy hat can be made at the hatters table, nothing like a pile of cowboy hats on the floor)

Both hats can be made at the bench. I made the mistake not adding them to the category "headgear" when switching around all the hats. Issue has been reported on the forums and I fixed it already. Will be included in the next release. 

> With this new group my colonist just started standing around outside my kitchen/cooler area. 

As for the job tick error I would need the output log and if possible the .rws savegame with the error.

**Comment by Fredfirebat** [comment] 2016-01-08 03:33
[output_log.txt](https://github.com/simon-82/ModVarietyPack/files/82077/output_log.txt)

Sorry about the delay there and as for the savegame it doesnt seem that I can post it here but i do still have it and will back it up if there is another way I can send it your way.

**Comment by simon-82** [comment] 2016-01-08 10:00
Thanks for the log. :+1: 
Unfortunately it looks like I expected. The output is very vague and without taking a closer look ingame, it's very hard to find out more about the error. With the savegame I can use the various other debug tools to maybe find the cause. 

As for sending the file my way, there are various options. I don't know what you are using, but maybe google drive, dropbox, or just make a new repo and upload it to that.

**Comment by Fredfirebat** [comment] 2016-01-08 12:32
https://www.dropbox.com/s/i41upyt4o2q0k01/Planeton.rws?dl=0

That should work let me know if it doesn't I won't be home for the next 16 hours but may be able to do something from my work computer

**Comment by TLHeart** [comment] 2016-01-08 21:39
Might want to get that hat fix out soon, as I loaded his save. The standing is coming from the outfits... and since they can only equip apparel that is in a stockpile, errors are being thrown. As soon as I added in the missing hats to the headgear, no more job errors.

**Comment by Fredfirebat** [comment] 2016-01-09 00:52
Ah thanks I'll set it up when I get home tonight hopefully.

**Comment by simon-82** [comment] 2016-01-09 14:30
Yep, seems to be solved by adding the headgear ThingCategory. Fixed in next release.

**Closed as completed by simon-82** 2016-01-09 14:30 UTC
